### Tensor Creations with PyTorch
#### 1d Tensor Creation

In [13]:
import torch
import random

In [14]:
x = torch.tensor(data=[1, 2, 3])
print(x)

tensor([1, 2, 3])


#### 2d Tensor Creation

In [15]:
x = torch.tensor(data=[[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


#### Declare with tensor type
Allows various math functions

In [16]:
x = torch.tensor(data=[1.3, .5, 6.3, 4.9], dtype=torch.float32, requires_grad=True)
print(x)

tensor([1.3000, 0.5000, 6.3000, 4.9000], requires_grad=True)


#### Random Tensor

In [17]:
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.4283, 0.2889, 0.4224, 0.3571],
         [0.9577, 0.1100, 0.2933, 0.9205],
         [0.5876, 0.1299, 0.6729, 0.1028]],

        [[0.7876, 0.5540, 0.4653, 0.2311],
         [0.2214, 0.3348, 0.4541, 0.2519],
         [0.6310, 0.1707, 0.3122, 0.1976]]])


#### Reproducibility - Setting the random seed

In [18]:
torch.manual_seed(23)

random.seed(23)

In [20]:
# Include this snippet to set a constant random state
torch.manual_seed(23)    # pick a number
random.seed(23)   # pick a numnber