### Tensor Creations with PyTorch
#### 1d Tensor Creation

In [8]:
import torch


In [10]:
x= torch.tensor(data=[1,2,3])
print(x)


tensor([1, 2, 3])


#### 2d Tensor Creation

In [11]:
x= torch.tensor(data=[[1,2,3], [4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


#### Declare with tensor type
Allows various math functions

In [14]:
x = torch.tensor(data=[1.3,.5,6.3, 4.9], dtype=torch.float32, requires_grad=True)
print(x)

tensor([1.3000, 0.5000, 6.3000, 4.9000], requires_grad=True)


#### Random Tensor

In [16]:
x = torch.rand(2,3,4)
print(x)

tensor([[[0.5880, 0.3091, 0.7517, 0.8194],
         [0.0328, 0.5577, 0.5963, 0.9971],
         [0.4737, 0.1621, 0.8912, 0.2322]],

        [[0.3057, 0.0765, 0.3429, 0.3398],
         [0.6320, 0.5035, 0.7732, 0.9262],
         [0.7242, 0.1028, 0.2545, 0.7762]]])


#### Reproducibility - Setting the random seed

In [17]:
torch.manual_seed(23)

# or 

import random
random.seed(23)

In [19]:
# Include this snippet to set a constant random state
import torch
import random

torch.manual_seed(23)  # pick a number
random.seed(23) # pick a numnber 